# Generated by Django 5.0.4 on 2024-04-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytransfer',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Сделано'),
        ),
    ]
