# Generated by Django 5.0.4 on 2024-04-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historytransfer_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historytransfer',
            options={'verbose_name': 'Перевод', 'verbose_name_plural': 'Переводы'},
        ),
    ]
