# Generated by Django 5.0.4 on 2024-04-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
    ]
