# Generated by Django 5.0.4 on 2024-04-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default=1, max_length=50, verbose_name='Подтверждения пароля'),
            preserve_default=False,
        ),
    ]
